Feature/jmt 116 other profile
GDSC-Daejin/jmt-web pull request #28
Opened 2023-07-11 11:45 UTC by Parkjinhye

## 작업 내용 (Content)
맛집 상세 페이지, 남 프로필 페이지 작업

## 기타 사항 (Etc)
중간 점검 pr

## Merge 전 필요 작업 (Checklist before merge)
- [ ] component 대소문자 확인
- [ ] conflict 해결
- [ ] tsc 오류 확인

## Merge 후 필요 작업 (Checklist after merge)
- PR이 생성되면 코드 리뷰 요청한 개발자에게 슬랙으로 알려주세요.

2023-07-11 12:11 UTC, HyeokE requested changes
굿굿 몇가지 수정사항이랑 궁금한 점이 있어서 코멘트 남겼습니다

2023-07-11 12:11 UTC, HyeokE commented on package.json
> +    "react-bootstrap": "^2.7.4",
요거 지워주세요!

2023-07-11 12:11 UTC, HyeokE commented on src/pages/PlaceDetail.tsx
> +                <div className={'text-m-medium'}>유저이름&nbsp;&nbsp;</div>
![CleanShot 2023-07-11 at 20 50 49](https://github.com/GDSC-Daejin/jmt-web/assets/61281239/e272b276-52b5-4811-b3cf-2a69c2b9a2ec)
중앙 정렬 안되어있습니다

2023-07-11 12:11 UTC, HyeokE commented on src/components/placeDetail/Information/index.tsx
> +        <AddressCopy
![CleanShot 2023-07-11 at 20 57 34](https://github.com/GDSC-Daejin/jmt-web/assets/61281239/0d1b604e-6596-466f-9a48-b08d225b7070)
중앙 정렬 안되어있어요

2023-07-11 12:11 UTC, HyeokE commented on src/layouts/PlaceDetail/DetailMenu/styled.ts
> +  width: 100vw- 40px;
css에서 계산이 필요할 때는 calc(100vw - 40px) 이렇게 작성하시면 돼요!

2023-07-11 12:11 UTC, HyeokE commented on src/layouts/PlaceDetail/DetailMenu/index.tsx
> +        <AnimateBlock
요고는 무슨 역할이에요??

2023-07-11 12:11 UTC, HyeokE commented on src/layouts/PlaceDetail/DetailMenu/index.tsx
> +      {selectedMenu === 0 ? (
각 조건을 숫자로 하신 이유가 있나요?

2023-07-11 12:11 UTC, HyeokE commented on src/layouts/PlaceDetail/Modal.tsx
> +  /* gray900 */
import {colors} from "@styles/theme/color";
로 불러와서 color: ${colors.gray900} 으로 사용하시면 됩니다!

2023-07-11 12:11 UTC, HyeokE commented on src/pages/OtherProfile.tsx
> +import '@styles/pages/OtherProfile.scss';
여기서 불러오지 않고 `styles/pages/_index.scss`에 해당 css 추가하시면 `index.tsx`로 전체 적용됩니다!

2023-07-11 12:11 UTC, HyeokE commented on src/pages/Home.tsx
> +/* eslint-disable import/order */
요건 추가한 이유가 있나요?

2023-07-11 12:11 UTC, HyeokE commented on src/store/DetailAtom.ts
> +export const detailAtom = atom(1);
요건 무슨 역할이에요?

2023-07-11 12:44 UTC, Parkjinhye commented on src/layouts/PlaceDetail/DetailMenu/index.tsx
> +        <AnimateBlock
홈의 탭같은 역할이요
![image](https://github.com/GDSC-Daejin/jmt-web/assets/90834208/c0956bf2-b15d-4573-891b-ab821c4499a2)
사진이 들어가나

2023-07-11 12:47 UTC, Parkjinhye commented on src/layouts/PlaceDetail/DetailMenu/index.tsx
> +      {selectedMenu === 0 ? (
const menuList = ['추천인 리뷰', '가게정보', '후기(' + count + ')'];  이렇게 배열로 메뉴를 만들어서
배열의 index 숫자로 움직이는 블럭 위치를 설정했어요 
left : 블럭width * index 
요런 느낌?

2023-07-11 12:51 UTC, Parkjinhye commented on src/pages/Home.tsx
> +/* eslint-disable import/order */
![image](https://github.com/GDSC-Daejin/jmt-web/assets/90834208/377fc12f-4404-4ceb-9749-db1681a791a9)
자꾸 저 오류떠서 보기싫어서 임시로 해놨어요.. 머쓱..

2023-07-11 12:52 UTC, Parkjinhye commented on src/store/DetailAtom.ts
> +export const detailAtom = atom(1);
맛집 상세 페이지로 이동할 때 가게의 id 정보를 atom으로 관리하는 게 낫지 않을까 해서 만들어봤어요

2023-07-12 05:20 UTC, HyeokE approved these changes
LGTM 수고하셨어요

2023-07-12 05:22 UTC, HyeokE commented on src/layouts/PlaceDetail/DetailMenu/index.tsx
> +      {selectedMenu === 0 ? (
아하 제 생각에는 각 메뉴에 대한 ID를 만들고 해당 ID가 있을 때 한글로 '후기(10)' 텍스트를 mapping하는게 더 좋지 않을까 싶은데 어떠신가요?
아래 조건문만 봤을 때 어떤 역할인지 모호하다는 생각이 들어요.

2023-07-12 05:24 UTC, HyeokE commented on src/store/DetailAtom.ts
> +export const detailAtom = atom(1);
가게의 id 정보는 URL로 관리하는게 좋을 것같아요.
/place/:id 이런식으로요
가게 상세 정보로 바로 이동해야할 때가 있을텐데 클라이언트에서 해당 주소로 바로 이동하려면 직관적인 URL로 하는게 좋을 것 같아요

2023-07-13 04:12 UTC, HyeokE requested changes

2023-07-13 04:12 UTC, HyeokE commented on src/hooks/getUrlValue.tsx
hooks 폴더에는 use로 시작하는 상태 hook들만 포함되어야 해요.
요런 함수는 utils 폴더로 옮기는게 좋을 것 같아요.

react-router-dom에는 useParams라는 훅이 있는데 이거 활용하셔도 될 것 같습니다.

2023-07-18 12:11 UTC, merged