Feature/jmt 116 other profile
GDSC-Daejin/jmt-web pull request #42
Opened 2023-09-06 05:02 UTC by Parkjinhye

## 작업 내용 (Content)
다른 유저 프로필 페이지, 신고 페이지, 맛집 상세 페이지 작업

## 기타 사항 (Etc)

## Merge 전 필요 작업 (Checklist before merge)
- [ ] component 대소문자 확인
- [ ] conflict 해결
- [ ] tsc 오류 확인

## Merge 후 필요 작업 (Checklist after merge)
- PR이 생성되면 코드 리뷰 요청한 개발자에게 슬랙으로 알려주세요.

2023-09-06 22:34 UTC, HyeokE requested changes
수고하셨습니다
아니 루시 엄청 잘하시는데요? 그냥 취업하세요 ㅋㅋ

2023-09-06 22:34 UTC, HyeokE commented on src/apis/common/restaurant/index.ts
> +export const getRestaurantByUser = async ({
함수 이름은 메서드와 데이터를 알아볼 수 있게 작성해주세요
post 메서드네용

2023-09-06 22:34 UTC, HyeokE commented on src/apis/hooks/restaurant/useGetRestaurantByUser.tsx
> +export const useGetRestaurantByUser = ({
여기도 동일하게 변경되어야할 것 같아요

2023-09-06 22:34 UTC, HyeokE commented on src/apis/hooks/user/useGetUserInfo.tsx
> +    //{ enabled: Boolean(id), suspense: true, staleTime: 20000 },
로딩처리가 있는게 좋을 것 같은데 통일을 위해서 Suspense를 쓰는게 좋지 않을까용

2023-09-06 22:34 UTC, HyeokE commented on src/assets/filter/index.tsx
> +  switch (iconName) {
스위치 케이스로 만드신 이유가 있나요?
저는 보통 object로 만드는데 그냥 궁금해서 여쭤봅니당

2023-09-06 22:34 UTC, HyeokE commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +  //바텀시트가 닫히고 열릴 때 마다 local정보 초기화 = 확인 버튼 클릭 전 정보 초기화
이전에 필터가 있다면 이전 선택지가 남아있는게 좋지 않을까요?
참고로 리셋은 jotai에서 RESET이라는 키워드를 제공해요!

2023-09-06 22:34 UTC, HyeokE commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +  //바텀시트가 닫히고 열릴 때 마다 local정보 초기화 = 확인 버튼 클릭 전 정보 초기화
오히려 이전 뷰로 이동했을 때 필터를 초기화하는게 더 자연스러울 것 같아요

2023-09-06 22:34 UTC, HyeokE commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +    setLocalDrink(item as DrinkCheck);
as 키워드를 안쓰고도 가능해보여요

2023-09-06 22:34 UTC, HyeokE commented on src/components/common/FilterBottomSheet/FoodCategoryFilter.tsx
> +    setLocalFood(item as FoodCheck);
요기도 마찬가지로 as를 안써도 될 것 같아요

2023-09-06 22:34 UTC, HyeokE commented on src/components/common/FilterBottomSheet/FoodCategoryFilter.tsx
> +            {Object.keys(FoodKey).map((item: string) => {
음식 키만 array로 빼신 것 같아요.
foodKeyList라는 리스트를 만들고 생성할 때 타입을 할당하면 좋을 것 같습니다
그럼 하단에 키를 사용할 때 as를 안써도 돼요!

2023-09-06 22:34 UTC, HyeokE commented on src/components/common/FilterBottomSheet/components/FooterButton.tsx
> +  const toggleBS = useSetAtom(toggleBottomSheet);
줄임말은 지양해주세용

2023-09-06 22:34 UTC, HyeokE commented on src/store/filterAtom.ts
> +// export const FoodCategoryState = {
주석 지워주세요!

2023-09-06 22:34 UTC, HyeokE commented on src/utils/getUrlValue.tsx
> +const getUrlValue = () => {
요거 저번에 어떤 용도로 사용한다고 하셨죠??
기억이 잘 안나네요 ㅜㅜ

2023-09-08 03:18 UTC, Parkjinhye commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +  //바텀시트가 닫히고 열릴 때 마다 local정보 초기화 = 확인 버튼 클릭 전 정보 초기화
이전 뷰로 이동했을 때 필터를 초기화한다는 게 page가 변하면(ex 홈->남의 프로필 & 남프로필->홈) 필터를 초기화하는게 자연스러울 것 같단 말씀이신가용?

2023-09-08 03:18 UTC, Parkjinhye commented on src/assets/filter/index.tsx
> +  switch (iconName) {
변환해주는 '함수'가 필요하다는 생각으로 변수와 return이 명확한 switch를 썼어요

2023-09-08 04:14 UTC, Parkjinhye commented on src/components/common/FilterBottomSheet/FoodCategoryFilter.tsx
> +            {Object.keys(FoodKey).map((item: string) => {
Object.keys(FoodKey)가 foodKeyList 아닌가요..?!
그리고 생성할 때 타입을 할당한다는 게 무슨 뜻인지 모르겠어요ㅠㅜ

2023-09-08 04:34 UTC, Parkjinhye commented on src/utils/getUrlValue.tsx
> +const getUrlValue = () => {
placeDetail 페이지쪽 구성이 depth가 좀 있어서 url주소의 마지막 숫자 값(레스토랑 아이디)를 받아와서 쓰고있어요

2023-09-10 02:54 UTC, HyeokE commented on src/assets/filter/index.tsx
> +  switch (iconName) {
음 저는 왜 함수가 필요한건지 궁금했어요 
함수는 스택으로 들어가서 실행되는데 object에 비해서 좋은 점이 어떤게 있을까요?

2023-09-10 02:55 UTC, HyeokE commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +  //바텀시트가 닫히고 열릴 때 마다 local정보 초기화 = 확인 버튼 클릭 전 정보 초기화
네네 맞아요!

2023-09-10 02:55 UTC, HyeokE commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +  //바텀시트가 닫히고 열릴 때 마다 local정보 초기화 = 확인 버튼 클릭 전 정보 초기화
맛집 상세로 갔다가 돌아오는건 유지
홈으로 갔다가 들어오는건 초기화
를 말한거에요

2023-09-10 02:56 UTC, HyeokE commented on src/components/common/FilterBottomSheet/FoodCategoryFilter.tsx
> +            {Object.keys(FoodKey).map((item: string) => {
아하 쉽게 얘기하면 가독성 측면에서 변수로 분리하자는 말이에요

2023-09-10 02:58 UTC, HyeokE commented on src/utils/getUrlValue.tsx
> +const getUrlValue = () => {
음..일단 유지하시죠! 더 좋은 방법이 생각났는데 공수가 살짝 들어서 완성하고 같이 개선해봐요ㅎㅎ

2023-09-11 02:35 UTC, Parkjinhye commented on src/assets/filter/index.tsx
> +  switch (iconName) {
object의 value에 string이나 number같은 단순한 값만 써서 그런지 component를 반환할 때 쓴다는 생각을 못했어요. 확실히 switch보다는 object가 실행이나 가독성 부분에서도 좋은 것 같아요!

2023-09-11 04:34 UTC, Parkjinhye commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +  //바텀시트가 닫히고 열릴 때 마다 local정보 초기화 = 확인 버튼 클릭 전 정보 초기화
초기화 되는 시점에 대해 내일 세션 끝나고 화공하면서 얘기할 수 있을까욤?

2023-09-11 10:40 UTC, HyeokE commented on src/assets/filter/index.tsx
> +  switch (iconName) {
ㅎㅎ 넵 이건 금방 개선할 수 있을 것 같은데 일단 배포하고 개선하시죠!

2023-09-11 10:40 UTC, HyeokE commented on src/components/common/FilterBottomSheet/DrinkCategoryFilter.tsx
> +  //바텀시트가 닫히고 열릴 때 마다 local정보 초기화 = 확인 버튼 클릭 전 정보 초기화
넵~ 그러시죠!

2023-09-19 11:31 UTC, HyeokE approved these changes

2023-09-19 11:32 UTC, merged